### ISSUE TITLE
Update Splash-screen

### ISSUE THREAD

**Issue by Alani25** [Candlestickers/Candlestick#1]
Update the main splash-screen to reflect **_candlestickers_** 

Along with this, we may need to also edit the description inside of the welcome menu: 
- cover version changes
- removing the Patreon section (since Patreon for Wick doesn't exist anymore)
- adding a disclaimer to let users know that this _is a fork_ of Wick Editor

**Comment by BaronAWC95014** [comment]
names are changed and patreon is removed, and slight modifications have been made to splash screen
